apiVersion: v1
kind: Service
metadata:
  name: ticket-dashboard-service
  namespace: ticket-dashboard
spec:
  selector:
    app: ticket-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort
