name: CI/CD Ticket Dashboard

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  quality-test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}murilloac/ticket-dashboard:latest .

      - name: Login no Docker Hub
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push da imagem para Docker Hub
        if: github.event_name == 'push'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ticket-dashboard:latest
